name: Pylint

on:
  push:
    branches: [main]
    paths:
      - "**/*.py"
  pull_request:
    branches: [main]
    paths:
      - "**/*.py"

jobs:
  shared:
    uses: ./.github/workflows/shared_workflow.yml
    with:
      python-version: "3.12"

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip install pylint

      - name: Analysing the code with pylint
        run: |
          files=$(git ls-files '*.py')
          if [ -n "$files" ]; then
            pylint $files --disable=all --enable=C0114,C0115,C0116,C0301 || true
          else
            echo "No Python files found for linting."
          fi
